<?php

namespace App\Enums;

/**
 * `PlanningAttendance` is a placeholder for when real attendance data exists
 * (docs/prompts/04-seguimiento-institucional.md §4) — the enum case exists,
 * but nothing produces it yet. Comments never open alerts on their own.
 */
enum AlertType: string
{
    case Performance = 'performance';
    case PlanningAttendance = 'planning_attendance';

    /**
     * "Alerta escalada con plazo vencido" (ClickUp 86e3jpzdp): generated by
     * `alerts:escalate` when an alert was handed off and its deadline passed
     * without the receiver choosing a way out. It speaks about the circuit
     * (who passed what to whom, and when), never about the student.
     */
    case EscalatedOverdue = 'escalated_overdue';
}
