<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

/**
 * Early-warning alert for a student, generated by `alerts:generate`
 * (docs/prompts/04-seguimiento-institucional.md §4) or, in the future, by
 * other rules. `planning_attendance` is a placeholder type for when real
 * attendance data exists — not generated yet.
 */
return new class extends Migration
{
    public function up(): void
    {
        Schema::create('alerts', function (Blueprint $table) {
            $table->id();
            $table->foreignId('school_id')->constrained()->cascadeOnDelete();
            $table->foreignId('student_id')->constrained()->cascadeOnDelete();
            $table->string('type');
            $table->string('severity');
            $table->text('description');
            $table->boolean('resolved')->default(false);
            $table->foreignId('resolved_by_id')->nullable()->constrained('users')->nullOnDelete();
            $table->timestamp('resolved_at')->nullable();
            $table->timestamps();

            $table->index(['school_id', 'student_id']);
            $table->index(['student_id', 'type', 'resolved']);
        });
    }

    public function down(): void
    {
        Schema::dropIfExists('alerts');
    }
};
