<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

/**
 * A follow-up someone scheduled on a student for a given date
 * (docs/prompts/17-seguimiento-programado.md §1). Nothing "expires" on its
 * own in Aula+ — the only thing that exists is a follow-up a person
 * programmed, with a due date, which may reach that date unresolved. Unlike
 * `alerts`, these are created by hand on a specific case, never generated by
 * a command.
 *
 * `description` and `resolution_note` may hold sensitive observations about a
 * minor, so they are excluded from the audit diff on the model (CLAUDE.md
 * security rule 11), same pattern as Comment/Accommodation/Alert.
 */
return new class extends Migration
{
    public function up(): void
    {
        Schema::create('scheduled_follow_ups', function (Blueprint $table) {
            $table->id();
            $table->foreignId('school_id')->constrained()->cascadeOnDelete();
            $table->foreignId('student_id')->constrained()->cascadeOnDelete();
            $table->text('description');
            $table->date('due_date');
            $table->foreignId('created_by_id')->constrained('users')->restrictOnDelete();
            $table->boolean('resolved')->default(false);
            $table->foreignId('resolved_by_id')->nullable()->constrained('users')->nullOnDelete();
            $table->timestamp('resolved_at')->nullable();
            $table->text('resolution_note')->nullable();
            $table->timestamps();

            $table->index(['school_id', 'student_id']);
            $table->index(['student_id', 'resolved', 'due_date']);
        });
    }

    public function down(): void
    {
        Schema::dropIfExists('scheduled_follow_ups');
    }
};
